In [ ]:
import os, sys, h5py
import numpy as np

hdf5_path = "/root/projects/diffusion_policy/data/cs_data/stack/demo_src_stack_task_D0/demo.hdf5"
f = h5py.File(hdf5_path, 'r')
print("Keys in the HDF5 file:")
for key in f.keys():
    print(key)

Keys in the HDF5 file:
data


In [2]:
from cnom_visualization import visualize_traj

actions = f['/data/demo_1/actions'][:]
pos_action = actions[:, :3]
print(f"actions:{pos_action[:10]}")

actions_from_eef = f["/data/demo_1/cs_info/eef_pose"]
pos_eef = actions_from_eef[:, :3, 3]
print(f"eef:{pos_eef[:10]}")

actions_from_world = f["/data/demo_1/cs_info/world_space_action"]
pos_world = actions_from_world[:, :3, 3]
print(f"world:{pos_world[:10]}")

actions:[[-0.09685559 -0.26412492 -0.07614617]
 [-0.17906143 -0.49955604 -0.14063916]
 [-0.24013064 -0.69201371 -0.18881627]
 [-0.28377969 -0.84519312 -0.22390855]
 [-0.31424663 -0.96343632 -0.24921833]
 [-0.34088101 -0.97823639 -0.30912521]
 [-0.28983406 -0.88075308 -0.24424475]
 [-0.28112522 -0.76279036 -0.31354621]
 [ 0.12134059 -0.42643813 -0.62676351]
 [ 0.35947235 -0.25825916 -0.5193912 ]]
eef:[[-0.06631647  0.01709103  1.04430798]
 [-0.06709166  0.01557154  1.04369182]
 [-0.06892014  0.01190501  1.0422636 ]
 [-0.07161066  0.00628398  1.04018839]
 [-0.07495257 -0.00107605  1.03762985]
 [-0.0787766  -0.00999784  1.03471396]
 [-0.08248106 -0.02131827  1.03167612]
 [-0.0866079  -0.02951403  1.02826555]
 [-0.09248396 -0.04258312  1.02307904]
 [-0.09660594 -0.0528322   1.01490004]]
world:[[-0.07115925  0.00388478  1.04050067]
 [-0.07604473 -0.00940626  1.03665986]
 [-0.08092667 -0.02269567  1.03282279]
 [-0.08579964 -0.03597568  1.02899296]
 [-0.09066491 -0.04924786  1.02516894]
 [-0.

In [6]:
dis1 = np.linalg.norm(pos_eef[0]-pos_eef[1])
print(f"Distance between eef: {dis1}")

dis2 = np.linalg.norm(pos_world[0]-pos_world[1])
print(f"Distance between world: {dis2}")

Distance between eef: 0.0018136719163334139
Distance between world: 0.014672134230895334
